### ISSUE TITLE
[help] Some help to use the plugin !

### ISSUE THREAD

**Issue by jacqueslelezard** [Wizcorp/cordova-plugin-moodstocks#1]
Hi!
May I ask you some help on how to launch moodstock from my js file ? I installed your plugin but I can't launch the scan...

**Comment by jacqueslelezard** [comment]
Okay, I managed to use it, I will push a more detailed version of the readme file fot other users :)

**Comment by ronkorving** [comment]
Pull requests always appreciated :) Thanks
